# Generated by Django 4.1 on 2023-10-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('to_do', 'to do'), ('assigned', 'assigned'), ('in_progress', 'in progress'), ('under_review', 'under review'), ('done', 'done')], max_length=20),
        ),
    ]
